### PR TITLE
get comment string

### PR DESCRIPTION
**Pull request by dnaaun**
This is in support of [the VSCode variables PR](https://github.com/ms-jpq/coq_nvim/pull/289) in coq.

### CODE REVIEW

**Comment by ms-jpq** [comment]
ok im gonna have to reject this PR, sorry :(, hope you wont'd mind

the reason is that I REALLY want to stay away from storing language specific details in my library code, at the very least, it should be a json or yaml config.

**Comment by dnaaun** [comment]
> ok im gonna have to reject this PR, sorry :(, hope you wont'd mind

How you gonna do me like that ms-jpq? I thought we were friends 😆  /sarcasm

**Comment by ms-jpq** [comment]
im sorry!,  i feel terrible rejecting PRs.

but i think its important to keep things in the right places

**Comment by ms-jpq** [comment]
I really do appreciate your work!

thank you!

**Comment by dnaaun** [comment]
> im sorry!, i feel terrible rejecting PRs.

What no, don't feel bad at all! I was totally kidding haha. I totally understand. I'm super grateful for your work.

**Comment by dnaaun** [comment]
Anyways, I would be glad to remove the part that has language-specific detail (and just rely on the `commentstring` option). Does that sound good?

**Comment by ms-jpq** [comment]
its already merged and has everything! you can pull latest and test it out!

**Comment by ms-jpq** [comment]
thank you for the work on the PR

**Comment by dnaaun** [comment]
You're actually right. Thanks a bunch!

**Pull request closed without merging**
